sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t sites.azurecr.io/enecorunners.nl .
  - docker login -u sites -p "$DOCKER_PASSWORD" sites.azurecr.io

script:
  - docker push sites.azurecr.io/enecorunners.nl